language: node_js
node_js:
  - "10"
cache:
  directories:
  - node_modules
notifications:
  email: false
deploy:
  provider: script
  skip_cleanup: true
  script: sh ./scripts/update-version.sh
  on:
    branch: master
branches:
  only:
  - master
